apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dbs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/marcksdbgg/m8-manifest'
    targetRevision: HEAD
    path: platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dbs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true